"""
autosetter.hf_model
===================
HuggingFace Transformers client for running the fine-tuned Qwen 7B model
(winglian/qwen-2.5-codeforces-cot-kd-v1) locally on GPU.

This module is responsible for generating ONLY the following four artifacts
from problem.json:

    1. statement.tex   — LaTeX problem statement (Codeforces/Polygon style)
    2. solution.cpp    — Optimal/reference C++17 solution
    3. brute.cpp       — Correct brute-force solution for stress testing
    4. checker.cpp     — Output checker using testlib.h

All other artifacts (validator, generator, solution_wa, solution_tle) continue
to be generated by the existing Ollama-based pipeline in llm.py.

Design Notes:
    - The model is loaded lazily on first inference call and cached as a
      module-level singleton to avoid redundant GPU memory allocation when
      generate_text() is called multiple times during a single pipeline run.
    - The client uses HuggingFace's AutoModelForCausalLM + AutoTokenizer to
      load the model, with automatic device mapping via the `accelerate`
      library for multi-GPU or mixed-precision setups.
    - All generation parameters (max_new_tokens, temperature, top_p) are
      configurable both at construction time and per-call.

Dependencies:
    - torch >= 2.0.0
    - transformers >= 4.40.0
    - accelerate >= 0.30.0
"""

from __future__ import annotations

import logging
from typing import Optional

# ─────────────────────────────────────────────────────────────────────────────
# Import HuggingFace Transformers and PyTorch.
# These are REQUIRED dependencies for this module. If they are missing,
# a clear ImportError is raised at module import time so that the rest of
# AutoSetter can still function when this module is not used.
# ─────────────────────────────────────────────────────────────────────────────
try:
    import torch  # PyTorch — tensor operations, GPU memory management
    from transformers import (  # HuggingFace Transformers — model loading and tokenization
        AutoModelForCausalLM,  # Auto-detects the correct model class for causal LM
        AutoTokenizer,  # Auto-detects the correct tokenizer for the model
    )
except ImportError as _import_err:
    raise ImportError(
        "The HuggingFace model client requires 'torch', 'transformers', and "
        "'accelerate' packages. Install them with:\n"
        "  pip install torch transformers accelerate\n"
        f"Original error: {_import_err}"
    ) from _import_err

# ─────────────────────────────────────────────────────────────────────────────
# Import default configuration values for the HuggingFace model.
# These are defined in autosetter/config.py and can be overridden via
# environment variables (AUTOSETTER_HF_MODEL, AUTOSETTER_HF_DEVICE, etc.).
# ─────────────────────────────────────────────────────────────────────────────
from autosetter.config import (
    DEFAULT_HF_DEVICE,
    DEFAULT_HF_MAX_NEW_TOKENS,
    DEFAULT_HF_MODEL_NAME,
)

# ─────────────────────────────────────────────────────────────────────────────
# Module-level logger for diagnostic output (model loading progress, etc.).
# ─────────────────────────────────────────────────────────────────────────────
logger = logging.getLogger(__name__)


# =============================================================================
# Custom Exception
# =============================================================================


class HFModelError(Exception):
    """
    Raised when the HuggingFace model fails to load, tokenize, or generate.

    This exception is analogous to OllamaCallError in llm.py and is caught
    by the generator module to provide clear error messages to the user.
    """


# =============================================================================
# Module-Level Singleton Cache
# =============================================================================
# The model and tokenizer are heavy objects (~14 GB VRAM for float16).
# We cache them at the module level so they are loaded exactly once per
# process lifetime, even if generate_text() is called multiple times
# (e.g., once for each of the four artifacts).
# =============================================================================

_cached_model: Optional[AutoModelForCausalLM] = None  # Cached model instance
_cached_tokenizer: Optional[AutoTokenizer] = None  # Cached tokenizer instance
_cached_model_name: Optional[str] = None  # Name of the currently cached model


def _load_model_and_tokenizer(
    model_name: str,
    device: str,
) -> tuple:
    """
    Load the HuggingFace model and tokenizer, using the module-level cache.

    If the model has already been loaded with the same model_name, this
    function returns the cached instances immediately (no redundant loading).

    Parameters
    ----------
    model_name : str
        HuggingFace Hub model identifier or local path.
        Default: "winglian/qwen-2.5-codeforces-cot-kd-v1"
    device : str
        Device specification for model placement.
        - "auto"  : Let accelerate choose the best device(s) automatically.
        - "cuda"  : Force GPU (will fail if no CUDA device is available).
        - "cpu"   : Force CPU (very slow for 7B models, not recommended).

    Returns
    -------
    tuple
        (model, tokenizer) — the loaded and ready-to-use instances.

    Raises
    ------
    HFModelError
        If the model or tokenizer fails to load (network error, OOM, etc.).
    """
    global _cached_model, _cached_tokenizer, _cached_model_name

    # ── Return cached instances if the same model is already loaded ──
    if (
        _cached_model is not None
        and _cached_tokenizer is not None
        and _cached_model_name == model_name
    ):
        logger.debug(
            "HF model '%s' already loaded — returning cached instance.", model_name
        )
        return _cached_model, _cached_tokenizer

    # ── Load the tokenizer first (lightweight, fast) ──
    logger.info("Loading HuggingFace tokenizer for '%s'...", model_name)
    try:
        tokenizer = AutoTokenizer.from_pretrained(
            model_name,
            trust_remote_code=True,  # Required for Qwen models' custom tokenizer code
        )
    except Exception as exc:
        raise HFModelError(
            f"Failed to load tokenizer for model '{model_name}': {exc}"
        ) from exc

    # ── Load the model (heavy — allocates GPU memory) ──
    logger.info(
        "Loading HuggingFace model '%s' on device='%s'...", model_name, device
    )
    try:
        model = AutoModelForCausalLM.from_pretrained(
            model_name,
            # ── dtype: Use float16 for GPU efficiency. This halves VRAM usage
            #    compared to float32 while maintaining generation quality. ──
            torch_dtype=torch.float16,
            # ── device_map: When set to "auto", the accelerate library
            #    automatically distributes model layers across available GPUs
            #    and CPU RAM. When set to "cuda" or "cpu", forces a single
            #    device placement. ──
            device_map=device,
            # ── trust_remote_code: Required for Qwen model architecture code
            #    that is hosted alongside the weights on HuggingFace Hub. ──
            trust_remote_code=True,
        )
    except Exception as exc:
        raise HFModelError(
            f"Failed to load model '{model_name}' on device '{device}': {exc}. "
            f"If you are running out of GPU memory, try setting "
            f"AUTOSETTER_HF_DEVICE=cpu or using a quantized variant."
        ) from exc

    # ── Put the model into evaluation mode ──
    # This disables dropout layers and batch normalization updates that are
    # only needed during training, ensuring deterministic inference behavior.
    model.eval()

    # ── Cache the loaded instances for future calls ──
    _cached_model = model
    _cached_tokenizer = tokenizer
    _cached_model_name = model_name

    logger.info("HF model '%s' loaded successfully.", model_name)

    return model, tokenizer


# =============================================================================
# Main Client Class
# =============================================================================


class HFModelClient:
    """
    Client for generating text using the fine-tuned Qwen 7B model via
    HuggingFace Transformers, running locally on GPU.

    This client is used ONLY for generating the four artifacts that are
    within scope of the fine-tuned model:
        - statement.tex
        - solution.cpp
        - brute.cpp
        - checker.cpp

    Usage
    -----
    >>> client = HFModelClient()
    >>> response = client.generate_text("Write a C++17 solution for ...")
    >>> print(response)

    Parameters
    ----------
    model_name : str
        HuggingFace Hub model identifier.
        Default: "winglian/qwen-2.5-codeforces-cot-kd-v1"
    device : str
        Device placement strategy ("auto", "cuda", or "cpu").
        Default: "auto"
    max_new_tokens : int
        Maximum number of new tokens to generate per inference call.
        Default: 4096 (sufficient for most competitive programming artifacts)
    """

    def __init__(
        self,
        model_name: str = DEFAULT_HF_MODEL_NAME,
        device: str = DEFAULT_HF_DEVICE,
        max_new_tokens: int = DEFAULT_HF_MAX_NEW_TOKENS,
    ) -> None:
        # ── Store configuration parameters ──
        # These are saved as instance attributes so they can be inspected
        # or logged later without re-reading environment variables.
        self.model_name = model_name  # e.g. "winglian/qwen-2.5-codeforces-cot-kd-v1"
        self.device = device  # e.g. "auto", "cuda", "cpu"
        self.max_new_tokens = max_new_tokens  # e.g. 4096

        # ── Model and tokenizer are NOT loaded here ──
        # They are loaded lazily on the first call to generate_text().
        # This avoids allocating ~14 GB of GPU memory if the client is
        # instantiated but never used (e.g., when --skip-validation is set
        # and no generation is needed).
        self._model = None  # Will be set by _ensure_loaded()
        self._tokenizer = None  # Will be set by _ensure_loaded()

    def _ensure_loaded(self) -> None:
        """
        Ensure the model and tokenizer are loaded and ready for inference.

        This method is called at the start of every generate_text() call.
        It is a no-op if the model is already loaded (singleton cache hit).
        """
        if self._model is None or self._tokenizer is None:
            # Load via the module-level singleton cache function
            self._model, self._tokenizer = _load_model_and_tokenizer(
                model_name=self.model_name,
                device=self.device,
            )

    def generate_text(
        self,
        prompt: str,
        max_new_tokens: Optional[int] = None,
        temperature: float = 0.2,
        top_p: float = 0.95,
    ) -> str:
        """
        Generate text from the fine-tuned Qwen 7B model given a prompt.

        This method handles the complete inference pipeline:
            1. Ensure model is loaded (lazy initialization).
            2. Tokenize the input prompt.
            3. Move input tensors to the model's device.
            4. Run forward pass with autoregressive generation.
            5. Decode the generated token IDs back to text.
            6. Strip the original prompt from the output (return only new tokens).

        Parameters
        ----------
        prompt : str
            The fully rendered prompt text (already has problem JSON injected).
        max_new_tokens : Optional[int]
            Override the default max_new_tokens for this specific call.
            If None, uses self.max_new_tokens.
        temperature : float
            Sampling temperature. Lower = more deterministic.
            Default: 0.2 (same as the Ollama pipeline for consistency).
        top_p : float
            Nucleus sampling probability threshold.
            Default: 0.95 (standard value for code generation).

        Returns
        -------
        str
            The generated text response (prompt portion stripped).

        Raises
        ------
        HFModelError
            If tokenization, inference, or decoding fails.
        """
        # ── Step 1: Ensure model and tokenizer are loaded ──
        self._ensure_loaded()

        # ── Determine the effective max_new_tokens for this call ──
        effective_max_tokens = max_new_tokens or self.max_new_tokens

        # ── Step 2: Tokenize the input prompt ──
        # The tokenizer converts the text prompt into a sequence of integer
        # token IDs that the model can process. return_tensors="pt" returns
        # PyTorch tensors directly.
        try:
            inputs = self._tokenizer(
                prompt,
                return_tensors="pt",  # Return PyTorch tensors
            )
        except Exception as exc:
            raise HFModelError(
                f"Failed to tokenize prompt for model '{self.model_name}': {exc}"
            ) from exc

        # ── Step 3: Move input tensors to the model's device ──
        # The model may be on GPU while the tokenizer outputs CPU tensors.
        # We need to ensure they are on the same device for the forward pass.
        try:
            input_device = self._model.device  # Get the device the model is on
            inputs = {
                key: value.to(input_device)  # Move each tensor to model's device
                for key, value in inputs.items()
            }
        except Exception as exc:
            raise HFModelError(
                f"Failed to move input tensors to device '{self._model.device}': {exc}"
            ) from exc

        # ── Record the length of the input prompt in tokens ──
        # We need this to strip the prompt tokens from the output later,
        # since the model generates [prompt_tokens + new_tokens] and we
        # only want to return the new_tokens portion.
        input_length = inputs["input_ids"].shape[1]

        # ── Step 4: Run autoregressive generation ──
        # torch.no_grad() disables gradient computation, which:
        #   - Reduces memory usage (no gradient tensors stored)
        #   - Speeds up inference (no backward pass overhead)
        try:
            with torch.no_grad():
                output_ids = self._model.generate(
                    **inputs,
                    # ── max_new_tokens: Limits how many NEW tokens are generated
                    #    (does not count the input prompt tokens). ──
                    max_new_tokens=effective_max_tokens,
                    # ── temperature: Controls randomness of token sampling.
                    #    0.0 = greedy (always pick highest probability token)
                    #    1.0 = fully random sampling from the distribution
                    #    0.2 = slightly random, mostly deterministic (good for code) ──
                    temperature=temperature,
                    # ── top_p (nucleus sampling): Only consider tokens whose
                    #    cumulative probability mass is within the top_p threshold.
                    #    0.95 = consider the smallest set of tokens that together
                    #    have 95% probability mass. ──
                    top_p=top_p,
                    # ── do_sample: Must be True when temperature > 0 to enable
                    #    probabilistic sampling. If False, generation is purely
                    #    greedy regardless of temperature. ──
                    do_sample=temperature > 0.0,
                    # ── pad_token_id: Use the EOS token as padding token.
                    #    Many causal LM models don't have a dedicated pad token,
                    #    so we use eos_token_id to avoid warnings. ──
                    pad_token_id=self._tokenizer.eos_token_id,
                )
        except Exception as exc:
            raise HFModelError(
                f"Model inference failed for '{self.model_name}': {exc}"
            ) from exc

        # ── Step 5: Decode generated tokens back to text ──
        # We slice output_ids to exclude the input prompt tokens ([:, input_length:])
        # so we only decode the newly generated portion.
        try:
            generated_ids = output_ids[:, input_length:]  # Strip prompt tokens
            generated_text = self._tokenizer.decode(
                generated_ids[0],  # First (and only) batch element
                skip_special_tokens=True,  # Remove <eos>, <pad>, etc.
            )
        except Exception as exc:
            raise HFModelError(
                f"Failed to decode generated tokens for '{self.model_name}': {exc}"
            ) from exc

        # ── Step 6: Validate that we got non-empty output ──
        if not generated_text.strip():
            raise HFModelError(
                f"Model '{self.model_name}' returned an empty response. "
                f"This may indicate the prompt is too long (input_length={input_length} tokens), "
                f"max_new_tokens is too small ({effective_max_tokens}), or the model "
                f"encountered an issue. Try increasing AUTOSETTER_HF_MAX_TOKENS."
            )

        # ── Return the clean generated text ──
        return generated_text.strip()
